# ~/.config/starship.toml

# Inserts a blank line between shell prompts

add_newline = true

# Command Time out

scan_timeout = 10000
command_timeout = 10000

# Change the default prompt format

format = """
[╭╴](bold purple)$os\
| $username\
$directory $fill $shell \
$git_branch\
$git_status\
$lua\
$terraform\
$vagrant\
$docker_context\
$helm\
$python\
$nodejs\
$ruby\
$kubernetes\
$kubernetes
[╰─](bold red)$character\
"""
# Right_format

# right_format = """ -- re-enabe for time and battery percentage
# $time\
# $cmd_duration
# $battery\
# """

# A continuation prompt that displays two filled in arrows

continuation_prompt = '▶▶ '

# Change the default prompt characters

[character]
success_symbol = "[](238)"
error_symbol = "[ ](fg:9)"
# error_symbol = "[](red)"


[profiles]
short = """
 $directory $fill \
 $time \
\n 󰤹  \
"""

# Change default Fill style
[fill]
# symbol = '=-='
symbol = ' '

# No need for env variables as starship provides a way to show your current distro

[os]
disabled = false
style = "fg:255"
format = "[$symbol]($style)"

[os.symbols]
Windows = " "
Linux = ""
Arch = "󰣇 "
Debian =" "
Fedora =" "
Ubuntu = " "
EndeavourOS = " "

#Directory settings

[directory]
truncation_length = 5
truncation_symbol = "…/"
home_symbol = "|  ~"
read_only_style = "197"
read_only = "  "
format = " at [$path]($style)[$read_only]($read_only_style)"

# Shows the username

[username]
style_user = "bold blue"
style_root = "bold purple"
format = "💜 [$user]($style)"
disabled = false  # disable in powershell
show_always = true

# Shows the prompt for the root user
#[root]
#format = "[$user]($style) "
#disabled = false
#show_always = true

# Shows the shell

[shell]
bash_indicator = "bash  _"
fish_indicator = "󰈺 󱢺 "
# zsh_indicator = " _"
zsh_indicator = "zsh  _"
powershell_indicator = "󰨊 "
ion_indicator =" "
elvish_indicator = " "
tcsh_indicator = "󰓸 "
xonsh_indicator = " "
cmd_indicator = " "
nu_indicator = "󱄆 "
unknown_indicator = " "
style = "cyan bold"
# format = "󰫵󰫲󱎦󱎦• [$indicator]($style) "
format = "[$indicator]($style) "
disabled = false

# Shows the battery

[battery]
full_symbol = "•"
charging_symbol = "⇡"
discharging_symbol = "⇣"
format = " [$symbol $percentage ]($style) "
disabled = false
#show_always = true

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 10
style = 'bold red'

[[battery.display]] # 'red' style and discharging_symbol when capacity is between 20% and 30%
threshold = 20
style = 'red'

[[battery.display]] # 'light red' style and discharging_symbol when capacity is between 20% and 30%
threshold = 30
style = 'light red'

[[battery.display]] # 'light yellow' style and discharging_symbol when  capacity is between 30% and 40%
threshold = 40
style = 'light yellow'

[[battery.display]] # 'yellow' style and discharging_symbol when  capacity is between 40% and 50%
threshold = 50
style = 'yellow'

[[battery.display]] # 'bold yellow' style and discharging_symbol when  capacity is between 50% and 60%
threshold = 60
style = 'bold yellow'

[[battery.display]] # 'light green' style and discharging_symbol when  capacity is between 60% and 70%
threshold = 60
style = "70"

[[battery.display]] # 'green' style and discharging_symbol when  capacity is between 70% and %80
threshold = 70
style = "green"

[[battery.display]] # 'bold green' style and discharging_symbol when  capacity is between 80% and 90%
threshold = 80
style = "bold green"

[[battery.display]] # 'cyan' style and discharging_symbol when  capacity is between 90% and 100%
threshold = 90
style = "cyan"

[[battery.display]] # 'bold cyan' style and discharging_symbol when  capacity is between 100% and 110%
threshold = 100
style = "bold cyan"

# Shows the time

[time]
disabled = false
style = "253"
format = "󱑂(255) [$time]($style) "

# Shows the CMD duration

[cmd_duration]
min_time = 10
format = "| 󰔚 [$duration]($style) "
style = "yellow"

# Shows the app directory/contents

[git_branch]
symbol = "󰊢  (yellow)"
format = "on [$symbol  $branch]($style) "
truncation_length = 7
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = "  "
untracked = "  "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " 󰏗 "
modified = "  "
staged = '[++\($count\)](green)'
renamed = " 󰖷 "
deleted = "  "

[lua]
format = "via [󰢱 󰍆 lua $version]($style)"

[terraform]
format = "via [󱁢  terraform $version]($style) 壟 [$workspace]($style)"

[vagrant]
format = "via [  vagrant $version]($style)"

[docker_context]
format = "via [󰡨  $context](bold blue)"
 
[helm]
format = "via [󰷀  $version](bold purple)"

[python]
symbol = "[󰌠 󱔎 ](blue)"
python_binary = "python3"

[nodejs]
format = "via [ 󰎙 $version](bold green)"
disabled = true

[ruby]
format = "via [󰫏  $version]($style)"

[kubernetes]
format = 'on [󰠳  $context\($namespace\)](bold purple)'
disabled = false

[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"

